---
- name: reload nfs exports
  ansible.builtin.command: exportfs -ra
  notify:
    - restart nfs server

- name: restart nfs server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
  failed_when: false
